spring:
 datasource:
  driver-class-name:  com.mysql.jdbc.Driver
  url:  jdbc:mysql://localhost:3306/eshopdb?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC
  username: julia
  password: julia
 jpa:
  show-sql: true
  properties:
   hibernate:
    dialect:  org.hibernate.dialect.MySQL5Dialect
    ddl-auto: update
   hikari:
    minimum-idle: 5
    maximum-pool-size:  10
