eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
ribbon:
  ReadTimeout: 10000
  
spring:
 datasource:
  driver-class-name:  com.mysql.jdbc.Driver
  url:  jdbc:mysql://localhost:3306/eshopdb?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC
  username: julia
  password: julia
 jpa:
  show-sql: true
  properties:
   hibernate:
    dialect:  org.hibernate.dialect.MySQL5Dialect
    ddl-auto: update
   hikari:
    minimum-idle: 5
    maximum-pool-size:  10
#     idle-timeout: 30000
